package studio.manga.ai;

import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Primary;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestTemplate;
import studio.manga.memory.MemoryContext;
import studio.manga.memory.MemoryService;

@Component
@Primary
public class GeminiAiGateway implements AiGateway {
  private final MemoryService memoryService;
  private final String apiKey;
  private final RestTemplate restTemplate;

  public GeminiAiGateway() {
    this.memoryService = null;
    this.apiKey = System.getenv("GEMINI_API_KEY");
    this.restTemplate = new RestTemplate();
  }

  @Autowired
  public GeminiAiGateway(MemoryService memoryService) {
    this.memoryService = memoryService;
    this.apiKey = System.getenv("GEMINI_API_KEY");
    this.restTemplate = new RestTemplate();
  }

  @Override
  public AiProposal propose(AiRequest r) {
    String basis =
        r.selectedText() == null || r.selectedText().isBlank()
            ? "the current scene"
            : r.selectedText();

    String extraContext = "";

    if (memoryService != null && r.projectId() != null) {
      MemoryContext ctx = memoryService.retrieveContext(r.projectId(), r.action(), r.selectedText());
      if (!ctx.relevantEntities().isEmpty() || !ctx.relevantChunks().isEmpty()) {
        List<String> names = ctx.relevantEntities().stream().map(e -> e.name).limit(3).toList();
        if (!names.isEmpty()) {
          extraContext = "Grounded in Atlas characters/lore: " + String.join(", ", names) + ". ";
        }
        extraContext += ctx.summary();
      }
    }

    String prompt = "You are a manga editor and writer assistant. Keep your response brief, creative, and action-oriented.\n";
    prompt += "Context: " + extraContext + "\n";
    prompt += "User's current text focus: \"" + basis + "\"\n";
    prompt += "Task: " + getTaskPrompt(r.action());

    if (apiKey == null || apiKey.isBlank()) {
      return new AiProposal(
          "MOCK RESPONSE (No GEMINI_API_KEY set): " + getTaskPrompt(r.action()) + " based on: " + basis,
          "AI_SUGGESTION",
          "Set GEMINI_API_KEY environment variable to enable real AI generation.");
    }

    try {
      String url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=" + apiKey;
      
      Map<String, Object> requestBody = Map.of(
          "contents", List.of(
              Map.of("parts", List.of(
                  Map.of("text", prompt)
              ))
          )
      );

      HttpHeaders headers = new HttpHeaders();
      headers.setContentType(MediaType.APPLICATION_JSON);
      HttpEntity<Map<String, Object>> entity = new HttpEntity<>(requestBody, headers);

      Map<String, Object> response = restTemplate.postForObject(url, entity, Map.class);
      
      String generatedText = extractText(response);

      return new AiProposal(generatedText, "AI_SUGGESTION", "Generated by Gemini 2.5 Flash");
    } catch (Exception e) {
      e.printStackTrace();
      return new AiProposal("Error calling Gemini API: " + e.getMessage(), "ERROR", "Failed to generate");
    }
  }

  private String getTaskPrompt(String action) {
    switch (action.toUpperCase()) {
      case "CONTINUE":
        return "Write the next paragraph to continue the story naturally.";
      case "DIALOGUE":
        return "Rewrite the dialogue to increase dramatic tension.";
      case "BRAINSTORM":
        return "Suggest a plot twist or interesting visual element to explore next.";
      default:
        return "Provide creative feedback on the text.";
    }
  }

  @SuppressWarnings("unchecked")
  private String extractText(Map<String, Object> response) {
    try {
      List<Map<String, Object>> candidates = (List<Map<String, Object>>) response.get("candidates");
      Map<String, Object> firstCandidate = candidates.get(0);
      Map<String, Object> content = (Map<String, Object>) firstCandidate.get("content");
      List<Map<String, Object>> parts = (List<Map<String, Object>>) content.get("parts");
      return (String) parts.get(0).get("text");
    } catch (Exception e) {
      return "Could not parse response from Gemini.";
    }
  }
}
