package studio.manga.documents;
import studio.manga.identity.CurrentUser; import studio.manga.projects.*; import org.springframework.http.*; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import java.time.Instant; import java.util.*;
@RestController @RequestMapping("/api/projects") public class WorkspaceController {
 private final ProjectRepository projects; private final ChapterRepository chapters; private final DocumentRepository documents; private final DocumentVersionRepository versions; private final CurrentUser user;
 WorkspaceController(ProjectRepository p,ChapterRepository c,DocumentRepository d,DocumentVersionRepository v,CurrentUser u){projects=p;chapters=c;documents=d;versions=v;user=u;}
 @GetMapping public List<Project> list(){return projects.findByOwnerIdOrderByUpdatedAtDesc(user.id());}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) @Transactional public Project create(@RequestBody ProjectInput in){ Project p=projects.save(new Project(user.id(),in.title(),in.description())); Chapter c=chapters.save(new Chapter(p.id,"Chapter 1",1)); Document d=documents.save(new Document(p.id,c.id,"Opening scene","CHAPTER")); versions.save(new DocumentVersion(d)); return p; }
 @GetMapping("/{id}/workspace") public Workspace workspace(@PathVariable UUID id){ Project p=owned(id); return new Workspace(p,chapters.findByProjectIdOrderByPosition(id),documents.findByProjectIdOrderByUpdatedAtDesc(id)); }
 @PostMapping("/{id}/chapters") @ResponseStatus(HttpStatus.CREATED) @Transactional public Chapter addChapter(@PathVariable UUID id,@RequestBody TitleInput in){ owned(id); int next=chapters.findByProjectIdOrderByPosition(id).size()+1; Chapter c=chapters.save(new Chapter(id,in.title(),next)); Document d=documents.save(new Document(id,c.id,in.title(),"CHAPTER")); versions.save(new DocumentVersion(d)); return c; }
 @PostMapping("/{id}/documents") @ResponseStatus(HttpStatus.CREATED) @Transactional public Document addDocument(@PathVariable UUID id,@RequestBody CreateDocument in){ owned(id); String type=Optional.ofNullable(in.type()).orElse("NOTE").toUpperCase(); if(!Set.of("NOTE","OUTLINE","SCENE","OTHER").contains(type)) throw new IllegalArgumentException("Unsupported document type"); Document d=documents.save(new Document(id,null,in.title(),type)); versions.save(new DocumentVersion(d)); return d; }
 @GetMapping("/{id}/documents/{documentId}") public Document document(@PathVariable UUID id,@PathVariable UUID documentId){owned(id);return documents.findByIdAndProjectId(documentId,id).orElseThrow(()->new NoSuchElementException("Document not found"));}
 @PutMapping("/{id}/documents/{documentId}") @Transactional public Document save(@PathVariable UUID id,@PathVariable UUID documentId,@RequestBody SaveDocument in){owned(id); Document d=documents.findByIdAndProjectId(documentId,id).orElseThrow(()->new NoSuchElementException("Document not found")); boolean changed=!Objects.equals(d.content,in.content())||!Objects.equals(d.title,in.title()); if(changed){d.title=in.title();d.content=in.content();d.revision++;d.updatedAt=Instant.now(); versions.save(new DocumentVersion(d));} return documents.save(d);}
 @GetMapping("/{id}/documents/{documentId}/versions") public List<DocumentVersion> history(@PathVariable UUID id,@PathVariable UUID documentId){owned(id);return versions.findByDocumentIdOrderByRevisionDesc(documentId);}
 private Project owned(UUID id){return projects.findByIdAndOwnerId(id,user.id()).orElseThrow(()->new NoSuchElementException("Project not found"));}
 public record ProjectInput(String title,String description){} public record TitleInput(String title){} public record CreateDocument(String title,String type){} public record SaveDocument(String title,String content){} public record Workspace(Project project,List<Chapter> chapters,List<Document> documents){}
}
